### ISSUE TITLE
Issue (operation error ec2imds: GetRegion, canceled, context deadline exceeded)

### ISSUE THREAD

**Issue by golaneduard** [statsbomb/prometheus-msk-discovery#18]
### Summary
I have next issue, when deploying `prometheus-stack` helm chart on eks cluster with `prometheus-msk-discovery` as sidecar. I have next issue:
```
operation error ec2imds: GetRegion, canceled, context deadline exceeded
```

### Configurations of EKS cluster
All EKS Nodes has attached IAM Role that have next `Trust Relationship`:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```
And next policy:
```
{
    "Statement": [
        {
            "Action": [
                "kafka:ListClusters",
                "kafka:ListNodes"
            ],
            "Effect": "Allow",
            "Resource": [
                "*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```
### Question
If somebody can help me to find out, what is the cause of the problem, all requirements are met.

**Comment by golaneduard** [comment]
Was added env variable `AWS_REGION` and everything was working as a charm.
```
    containers:
      - name: prometheus-msk-discovery
        image: "{{ .Values.global.registry }}/prometheus-msk-discovery:latest"
        env:
        - name: AWS_REGION
          value: "eu-north-1"
        args:
        - -output
        - /config-out/msk_file_sd.yml
        volumeMounts:
        - name: config-out
          mountPath: /config-out
```
