### ISSUE TITLE
Documentation incomplete for Helm implementation

### ISSUE THREAD

**Issue by mikelorant** [statsbomb/prometheus-msk-discovery#8]
Documentation in the README is incomplete when it comes to adding this to an existing Prometheus cluster (deployed with Helm).

Following should be added:
```
server:
  extraVolumeMounts:
    - name: config-out
      mountPath: /etc/prometheus/config_out

  extraVolumes:
    - name: config-out
      emptyDir: {}
```

Without defining an extra volume to create, this volume cannot be shared between 2 containers in a pod. You also to need to mount this volume into the Prometheus server container.

Be aware this is related to the chart in the Prometheus community Helm chart repository.
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
